name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  run-linters:
    name: Lint & Jest
    runs-on: ubuntu-latest
    steps:
      - name: Check out Git repository
        uses: actions/checkout@v2
      - name: Set up Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 20.x
      - name: Install dependencies
        run: yarn --prefer-offline
      - name: Run linters
        run: yarn lint
  build:
    runs-on: ubuntu-latest
    name: Build and Test
    steps:
      - uses: actions/checkout@v2
        name: Check out repository
      - uses: actions/setup-node@v1
        name: Set up Node.js
        with:
          node-version: 20.x
